import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Navbar from "~/components/Navbar";

export const metadata: Metadata = {
  title: "Deadlock Calc",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/Ability_point.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="font-colus text-offwhite">
      <body className="bg-black/90 "
        style={{
          backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(/bg-deadlock.png)`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          minHeight: '100vh',
          margin: 0,
        }}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}