import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Deadlock Calc",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/Ability_point.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="font-colus text-offwhite">
      <body>{children}</body>
    </html>
  );
}
